version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ProtoVerge
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=http://localhost:3000
